---
title: "strings_and_factors"
author: "AnMei Chen"
date: "10/19/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis" , 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##stings vectors

```{r}
string_vec = c("my", "name", "is", "jeff")

# does something particular show up inside the string?
# strings are case sensitive
str_detect(string_vec, "jeff")
str_detect(string_vec, "m")

str_replace(string_vec, "jeff","Jeff")

# to remove a word from the string
str_replace(string_vec, "is", " ")
```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

# the symbol ^ represents the beginning of the line
str_detect(string_vec, "^i think")

# the symbol $ represents the end of the line
str_detect(string_vec, "i think$")
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"bush")
str_detect(string_vec,"Bush")

# use [] to look for either this one or that one
str_detect(string_vec,"[Bb]ush")

```



```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

# look for a pattern at the beginning that have a number and followed with all upper letters and lower letters
#the [] speficies a range
str_detect(string_vec, "^[0-9][a-zA-Z]")
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "711")

# look for 7 followed by anything and then follow by 11
# use . to represent anything
str_detect(string_vec, "7.11")
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

# to look for one side of the square bracket
# use \\ to indicates that the symbol you are looking for is not the special character in R
str_detect(string_vec, "\\[")
```




